using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;

namespace JikanDotNet;

#if NET10_0_OR_GREATER
[JsonSourceGenerationOptions()]
[JsonSerializable( typeof( JikanApiError ) )]
[JsonSerializable( typeof( BaseJikanResponse<Anime> ) )]
[JsonSerializable( typeof( BaseJikanResponse<AnimeEpisode> ) )]
[JsonSerializable( typeof( BaseJikanResponse<AnimeFull> ) )]
[JsonSerializable( typeof( BaseJikanResponse<AnimeStatistics> ) )]
[JsonSerializable( typeof( BaseJikanResponse<AnimeThemes> ) )]
[JsonSerializable( typeof( BaseJikanResponse<AnimeVideos> ) )]
[JsonSerializable( typeof( BaseJikanResponse<Character> ) )]
[JsonSerializable( typeof( BaseJikanResponse<CharacterFull> ) )]
[JsonSerializable( typeof( BaseJikanResponse<Club> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ClubRelations> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<AnimeCharacter>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<AnimeStaffPosition>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<CharacterAnimeographyEntry>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<CharacterMangaographyEntry>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<ClubStaff>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<ExternalLink>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<ForumTopic>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<Genre>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<HistoryEntry>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<ImagesSet>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<MangaCharacter>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<PersonAnimeographyEntry>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<PersonMangaographyEntry>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<Recommendation>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<VoiceActingRole>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ICollection<VoiceActorEntry>> ) )]
[JsonSerializable( typeof( BaseJikanResponse<Manga> ) )]
[JsonSerializable( typeof( BaseJikanResponse<MangaFull> ) )]
[JsonSerializable( typeof( BaseJikanResponse<MangaStatistics> ) )]
[JsonSerializable( typeof( BaseJikanResponse<MoreInfo> ) )]
[JsonSerializable( typeof( BaseJikanResponse<Person> ) )]
[JsonSerializable( typeof( BaseJikanResponse<PersonFull> ) )]
[JsonSerializable( typeof( BaseJikanResponse<Producer> ) )]
[JsonSerializable( typeof( BaseJikanResponse<ProducerFull> ) )]
[JsonSerializable( typeof( BaseJikanResponse<UserAbout> ) )]
[JsonSerializable( typeof( BaseJikanResponse<UserFavorites> ) )]
[JsonSerializable( typeof( BaseJikanResponse<UserFull> ) )]
[JsonSerializable( typeof( BaseJikanResponse<UserProfile> ) )]
[JsonSerializable( typeof( BaseJikanResponse<UserStatistics> ) )]
[JsonSerializable( typeof( BaseJikanResponse<UserUpdates> ) )]

[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<Anime>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<AnimeEpisode>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<AnimeUserUpdate>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<Character>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<Club>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<ClubMember>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<EpisodeVideo>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<Friend>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<Magazine>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<MalUrl>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<Manga>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<MangaUserUpdate>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<News>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<Person>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<Producer>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<RelatedEntry>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<Review>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<SeasonArchive>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<UserMetadata>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<UserRecommendation>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<WatchEpisode>> ) )]
[JsonSerializable( typeof( PaginatedJikanResponse<ICollection<WatchPromoVideo>> ) )]

internal partial class JikanSourceGeneratedContext : JsonSerializerContext;
#endif